const SESSION_SECRET = process.env.SESSION_SECRET;
const SERVER_PORT = process.env.SERVER_PORT;

const CLIENT = {
  URL: process.env.CLIENT_URL
}

const DB = {
  HOST: process.env.PGHOST,
  USER: process.env.PGUSER,
  DATABASE: process.env.PGDATABASE,
  PASSWORD: process.env.PGPASSWORD,
  PORT: process.env.PGPORT,
};

const GOOGLE = {
  CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL,
  CONSUMER_KEY: process.env.GOOGLE_CONSUMER_KEY,
  CONSUMER_SECRET: process.env.GOOGLE_CONSUMER_SECRET,
};

const FACEBOOK = {
  CALLBACK_URL: process.env.FACEBOOK_CALLBACK_URL,
  CONSUMER_KEY: process.env.FACEBOOK_CONSUMER_KEY,
  CONSUMER_SECRET: process.env.FACEBOOK_CONSUMER_SECRET,
};


export { SERVER_PORT, DB, SESSION_SECRET, GOOGLE, FACEBOOK, CLIENT };
